import { User, Issue } from './types';

export const mockUsers: User[] = [
  { id: 'user-1', name: 'Alia Reddy', role: 'Citizen', avatarUrl: 'https://picsum.photos/seed/101/100/100' },
  { id: 'user-2', name: 'Bhavin Shah', role: 'Head of Department', avatarUrl: 'https://picsum.photos/seed/102/100/100' },
  { id: 'user-3', name: 'Chirag Kumar', role: 'Engineer', avatarUrl: 'https://picsum.photos/seed/103/100/100' },
  { id: 'user-4', name: 'Deepa Iyer', role: 'Fund Manager', avatarUrl: 'https://picsum.photos/seed/104/100/100' },
  { id: 'user-5', name: 'Esha Verma', role: 'Approving Manager', avatarUrl: 'https://picsum.photos/seed/105/100/100' },
  { id: 'user-6', name: 'Farhan Ali', role: 'Contractor', avatarUrl: 'https://picsum.photos/seed/106/100/100' },
  { id: 'user-7', name: 'Gita Patel', role: 'Engineer', avatarUrl: 'https://picsum.photos/seed/107/100/100' },
];

export const mockIssues: Issue[] = [
  {
    id: 'issue-1',
    title: 'Large Pothole on Main Street',
    type: 'Pothole',
    location: '123 Main St, Anytown',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street, near the intersection with Oak Avenue. It has already caused a flat tire for one vehicle.',
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-20T10:00:00Z',
    status: 'Submitted',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-20T10:00:00Z', updatedBy: 'Alia Reddy', notes: 'Issue reported by citizen.' },
    ],
  },
  {
    id: 'issue-2',
    title: 'Streetlight Outage',
    type: 'Streetlight',
    location: 'Corner of Pine and Maple',
    description: 'The streetlight at the corner of Pine and Maple has been out for three nights. It is a very dark corner and feels unsafe.',
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-18T21:30:00Z',
    status: 'AssignedForVerification',
    assignedEngineerId: 'user-3',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-18T21:30:00Z', updatedBy: 'Alia Reddy', notes: 'Citizen submission.' },
      { status: 'AssignedForVerification', date: '2024-07-19T09:00:00Z', updatedBy: 'Bhavin Shah', notes: 'Assigned to Chirag Kumar for verification.' },
    ],
  },
  {
    id: 'issue-3',
    title: 'Overflowing Garbage Bin',
    type: 'Garbage',
    location: 'City Park, near playground',
    description: 'The main garbage bin near the playground in City Park is overflowing. Trash is starting to scatter around the area.',
    reportedBy: 'user-1',
    reportedAt: '2024-07-15T14:00:00Z',
    status: 'Approved',
    assignedEngineerId: 'user-7',
    assignedFundManagerId: 'user-4',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-15T14:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'AssignedForVerification', date: '2024-07-16T10:00:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-17T11:30:00Z', updatedBy: 'Gita Patel' },
      { status: 'PendingApproval', date: '2024-07-18T15:00:00Z', updatedBy: 'Deepa Iyer' },
      { status: 'Approved', date: '2024-07-19T16:45:00Z', updatedBy: 'Esha Verma', notes: 'Project approved for execution.' },
    ],
    verificationReport: {
      comments: 'Verified the overflowing bin. The issue is as reported. Requires immediate collection and possibly a second bin for this high-traffic area.',
      submittedAt: '2024-07-17T11:30:00Z',
    },
    estimationReport: {
      estimatedCost: 250,
      notes: 'Cost covers a special collection trip and installation of one additional standard-issue park bin.',
      submittedAt: '2024-07-18T15:00:00Z',
    },
  },
  {
    id: 'issue-4',
    title: 'Water Main Break',
    type: 'Water Leakage',
    location: '55 Elm Street',
    description: 'Water is gushing out from a crack in the pavement in front of 55 Elm Street. It looks like a water main break.',
    imageUrl: 'https://picsum.photos/seed/204/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-10T08:00:00Z',
    status: 'Resolved',
    assignedEngineerId: 'user-3',
    assignedFundManagerId: 'user-4',
    assignedContractorId: 'user-6',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-10T08:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'AssignedForVerification', date: '2024-07-10T08:15:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-10T09:30:00Z', updatedBy: 'Chirag Kumar' },
      { status: 'PendingApproval', date: '2024-07-10T11:00:00Z', updatedBy: 'Deepa Iyer' },
      { status: 'Approved', date: '2024-07-10T11:15:00Z', updatedBy: 'Esha Verma' },
      { status: 'AssignedToContractor', date: '2024-07-10T11:30:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'InProgress', date: '2024-07-10T14:00:00Z', updatedBy: 'Farhan Ali' },
      { status: 'Resolved', date: '2024-07-11T17:00:00Z', updatedBy: 'Farhan Ali', notes: 'Pipe replaced and road surface temporarily patched.' },
    ],
    verificationReport: { comments: 'Confirmed major water main break. Urgent action required.', submittedAt: '2024-07-10T09:30:00Z' },
    estimationReport: { estimatedCost: 5500, notes: 'Emergency repair, including excavation and new pipe section.', submittedAt: '2024-07-10T11:00:00Z' },
    contractorReport: {
      notes: 'Work completed as per spec.',
      beforeImageUrl: 'https://picsum.photos/seed/301/600/400',
      afterImageUrl: 'https://picsum.photos/seed/302/600/400',
      submittedAt: '2024-07-11T17:00:00Z'
    }
  },
  {
    id: 'issue-5',
    title: 'Broken Streetlight',
    type: 'Streetlight',
    location: '101 Baker Street',
    description: 'The streetlight outside my house is flickering constantly. It seems to be broken.',
    reportedBy: 'user-1',
    reportedAt: '2024-07-21T11:00:00Z',
    status: 'PendingApproval',
    assignedEngineerId: 'user-7',
    assignedFundManagerId: 'user-4',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-21T11:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'AssignedForVerification', date: '2024-07-21T11:30:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-22T09:00:00Z', updatedBy: 'Gita Patel' },
      { status: 'PendingApproval', date: '2024-07-22T14:00:00Z', updatedBy: 'Deepa Iyer', notes: 'Submitted for final approval' },
    ],
    verificationReport: {
      comments: 'Verified. The bulb and ballast need replacement.',
      submittedAt: '2024-07-22T09:00:00Z',
    },
    estimationReport: {
      estimatedCost: 150,
      notes: 'Standard cost for bulb and ballast replacement parts and labor.',
      submittedAt: '2024-07-22T14:00:00Z',
    },
  },
];
