import { User, Issue } from './types';
import { add } from 'date-fns';

export let mockUsers: User[] = [
  { id: 'user-1', name: 'Alia Reddy', role: 'Citizen', avatarUrl: 'https://picsum.photos/seed/101/100/100', email: 'alia.r@email.com', phone: '9876543210', active: true },
  { id: 'user-2', name: 'Bhavin Shah', role: 'Head of Department', avatarUrl: 'https://picsum.photos/seed/102/100/100', email: 'bhavin.s@gov.in', phone: '9876543211', department: 'Roads', active: true },
  { id: 'user-3', name: 'Chirag Kumar', role: 'Engineer', avatarUrl: 'https://picsum.photos/seed/103/100/100', email: 'chirag.k@gov.in', phone: '9876543212', department: 'Roads', zone: 'North', active: true },
  { id: 'user-4', name: 'Deepa Iyer', role: 'Fund Manager', avatarUrl: 'https://picsum.photos/seed/104/100/100', email: 'deepa.i@gov.in', phone: '9876543213', active: true },
  { id: 'user-5', name: 'Esha Verma', role: 'Approving Manager', avatarUrl: 'https://picsum.photos/seed/105/100/100', email: 'esha.v@gov.in', phone: '9876543214', active: true },
  { id: 'user-6', name: 'Farhan Ali', role: 'Contractor', avatarUrl: 'https://picsum.photos/seed/106/100/100', email: 'farhan.ali@contractors.com', phone: '9876543215', department: 'Sanitation', zone: 'West', active: true },
  { id: 'user-7', name: 'Gita Patel', role: 'Engineer', avatarUrl: 'https://picsum.photos/seed/107/100/100', email: 'gita.p@gov.in', phone: '9876543216', department: 'Water', zone: 'South', active: true },
  { id: 'user-8', name: 'Harish Mehta', role: 'Contractor', avatarUrl: 'https://picsum.photos/seed/108/100/100', email: 'harish.m@contractors.com', phone: '9876543217', department: 'Roads', zone: 'North', active: true },
  { id: 'user-9', name: 'Ishaan Chopra', role: 'Contractor', avatarUrl: 'https://picsum.photos/seed/109/100/100', email: 'ishaan.c@contractors.com', phone: '9876543218', department: 'Electrical', zone: 'East', active: false },
];

export let mockIssues: Issue[] = [
  {
    id: 'issue-1',
    title: 'Large Pothole on Main Street',
    type: 'Pothole',
    location: '123 Main St, Anytown',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street, near the intersection with Oak Avenue. It has already caused a flat tire for one vehicle.',
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-20T10:00:00Z',
    status: 'Submitted',
    currentRoles: ['Head of Department'],
    statusHistory: [
      { status: 'Submitted', date: '2024-07-20T10:00:00Z', updatedBy: 'Alia Reddy', notes: 'Issue reported by citizen.' },
    ],
    upvotes: 12,
    upvotedBy: [],
  },
  {
    id: 'issue-2',
    title: 'Streetlight Outage',
    type: 'Streetlight',
    location: 'Corner of Pine and Maple',
    description: 'The streetlight at the corner of Pine and Maple has been out for three nights. It is a very dark corner and feels unsafe.',
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-18T21:30:00Z',
    status: 'PendingVerificationAndEstimation',
    currentRoles: ['Engineer'],
    assignedEngineerId: 'user-3',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-18T21:30:00Z', updatedBy: 'Alia Reddy', notes: 'Citizen submission.' },
      { status: 'PendingVerificationAndEstimation', date: '2024-07-19T09:00:00Z', updatedBy: 'Bhavin Shah', notes: 'Assigned to Engineer for verification.' },
    ],
    upvotes: 5,
    upvotedBy: [],
    slaDays: 7,
    slaDeadline: add(new Date(), { days: 5 }).toISOString(),
  },
  {
    id: 'issue-3',
    title: 'Overflowing Garbage Bin',
    type: 'Garbage',
    location: 'City Park, near playground',
    description: 'The main garbage bin near the playground in City Park is overflowing. Trash is starting to scatter around the area.',
    reportedBy: 'user-1',
    reportedAt: '2024-07-15T14:00:00Z',
    status: 'Approved',
    currentRoles: ['Contractor'],
    assignedEngineerId: 'user-7',
    assignedFundManagerId: 'user-4',
    assignedContractorId: 'user-6',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-15T14:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'PendingVerificationAndEstimation', date: '2024-07-16T10:00:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-17T11:30:00Z', updatedBy: 'Gita Patel' },
      { status: 'Estimated', date: '2024-07-18T15:00:00Z', updatedBy: 'Deepa Iyer' },
      { status: 'PendingApproval', date: '2024-07-18T15:05:00Z', updatedBy: 'System' },
      { status: 'Approved', date: '2024-07-19T16:45:00Z', updatedBy: 'Esha Verma', notes: 'Project approved for execution. Assigned to Contractor.' },
    ],
    verificationReport: {
      comments: 'Verified the overflowing bin. The issue is as reported. Requires immediate collection and possibly a second bin for this high-traffic area.',
      submittedAt: '2024-07-17T11:30:00Z',
    },
    estimationReport: {
      estimatedCost: 250,
      notes: 'Cost covers a special collection trip and installation of one additional standard-issue park bin.',
      submittedAt: '2024-07-18T15:00:00Z',
    },
    upvotes: 28,
    upvotedBy: ['user-1'],
    slaDays: 5,
    slaDeadline: add(new Date('2024-07-16T10:00:00Z'), { days: 5 }).toISOString(),
  },
  {
    id: 'issue-4',
    title: 'Water Main Break',
    type: 'Water Leakage',
    location: '55 Elm Street',
    description: 'Water is gushing out from a crack in the pavement in front of 55 Elm Street. It looks like a water main break.',
    imageUrl: 'https://picsum.photos/seed/204/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-10T08:00:00Z',
    status: 'Closed',
    currentRoles: [],
    assignedEngineerId: 'user-3',
    assignedFundManagerId: 'user-4',
    assignedContractorId: 'user-6',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-10T08:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'PendingVerificationAndEstimation', date: '2024-07-10T08:15:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-10T09:30:00Z', updatedBy: 'Chirag Kumar' },
      { status: 'Estimated', date: '2024-07-10T11:00:00Z', updatedBy: 'Deepa Iyer' },
      { status: 'PendingApproval', date: '2024-07-10T11:05:00Z', updatedBy: 'System' },
      { status: 'Approved', date: '2024-07-10T11:15:00Z', updatedBy: 'Esha Verma' },
      { status: 'AssignedToContractor', date: '2024-07-10T11:30:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'InProgress', date: '2024-07-10T14:00:00Z', updatedBy: 'Farhan Ali' },
      { status: 'Resolved', date: '2024-07-11T17:00:00Z', updatedBy: 'Farhan Ali', notes: 'Pipe replaced and road surface temporarily patched.' },
      { status: 'PendingFinalVerification', date: '2024-07-12T09:00:00Z', updatedBy: 'System' },
      { status: 'Closed', date: '2024-07-12T13:00:00Z', updatedBy: 'Bhavin Shah', notes: 'Work verified by department head. Issue closed.' },
    ],
    verificationReport: { comments: 'Confirmed major water main break. Urgent action required.', submittedAt: '2024-07-10T09:30:00Z' },
    estimationReport: { estimatedCost: 5500, notes: 'Emergency repair, including excavation and new pipe section.', submittedAt: '2024-07-10T11:00:00Z' },
    contractorReport: {
      notes: 'Work completed as per spec.',
      beforeImageUrl: 'https://picsum.photos/seed/301/600/400',
      afterImageUrl: 'https://picsum.photos/seed/302/600/400',
      submittedAt: '2024-07-11T17:00:00Z'
    },
    upvotes: 52,
    upvotedBy: ['user-1'],
  },
  {
    id: 'issue-5',
    title: 'Broken Streetlight',
    type: 'Streetlight',
    location: '101 Baker Street',
    description: 'The streetlight outside my house is flickering constantly. It seems to be broken.',
    reportedBy: 'user-1',
    reportedAt: '2024-07-21T11:00:00Z',
    status: 'PendingApproval',
    currentRoles: ['Approving Manager'],
    assignedEngineerId: 'user-7',
    assignedFundManagerId: 'user-4',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-21T11:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'PendingVerificationAndEstimation', date: '2024-07-21T11:30:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Verified', date: '2024-07-22T09:00:00Z', updatedBy: 'Gita Patel' },
      { status: 'Estimated', date: '2024-07-22T14:00:00Z', updatedBy: 'Deepa Iyer' },
      { status: 'PendingApproval', date: '2024-07-22T14:05:00Z', updatedBy: 'System', notes: 'Submitted for final approval' },
    ],
    verificationReport: {
      comments: 'Verified. The bulb and ballast need replacement.',
      submittedAt: '2024-07-22T09:00:00Z',
    },
    estimationReport: {
      estimatedCost: 150,
      notes: 'Standard cost for bulb and ballast replacement parts and labor.',
      submittedAt: '2024-07-22T14:00:00Z',
    },
    upvotes: 3,
    upvotedBy: [],
  },
  {
    id: 'issue-6',
    title: 'Garbage Dumped on Roadside',
    type: 'Garbage',
    location: 'Near Highway 4 entrance',
    description: 'Someone has illegally dumped a large pile of construction debris on the side of the road.',
    imageUrl: 'https://picsum.photos/seed/206/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-23T15:00:00Z',
    status: 'Verified',
    currentRoles: ['Fund Manager'],
    assignedEngineerId: 'user-3',
    assignedFundManagerId: 'user-4',
    statusHistory: [
        { status: 'Submitted', date: '2024-07-23T15:00:00Z', updatedBy: 'Alia Reddy' },
        { status: 'PendingVerificationAndEstimation', date: '2024-07-23T15:30:00Z', updatedBy: 'Bhavin Shah' },
        { status: 'Verified', date: '2024-07-24T10:00:00Z', updatedBy: 'Chirag Kumar', notes: 'Verified illegal dumping. Forwarded for cost estimation.' },
    ],
    verificationReport: {
      comments: 'Confirming a large amount of construction debris, likely requires a truck and a team to clear.',
      submittedAt: '2024-07-24T10:00:00Z',
    },
    upvotes: 18,
    upvotedBy: [],
    slaDays: 15,
    slaDeadline: add(new Date('2024-07-23T15:30:00Z'), { days: 15 }).toISOString(),
  },
  {
    id: 'issue-7',
    title: 'Fallen Tree Blocking Road',
    type: 'Obstruction',
    location: 'Oak Lane',
    description: 'A large tree has fallen across Oak Lane during the storm last night, completely blocking traffic.',
    imageUrl: 'https://picsum.photos/seed/207/600/400',
    reportedBy: 'user-1',
    reportedAt: '2024-07-20T08:00:00Z',
    status: 'Escalated',
    currentRoles: ['Head of Department'],
    assignedEngineerId: 'user-3',
    statusHistory: [
      { status: 'Submitted', date: '2024-07-20T08:00:00Z', updatedBy: 'Alia Reddy' },
      { status: 'PendingVerificationAndEstimation', date: '2024-07-20T08:30:00Z', updatedBy: 'Bhavin Shah' },
      { status: 'Escalated', date: '2024-07-23T09:00:00Z', updatedBy: 'System', notes: 'SLA of 2 days breached. Escalated to Head of Department.' },
    ],
    upvotes: 45,
    upvotedBy: [],
    slaDays: 2,
    slaDeadline: new Date('2024-07-22T08:30:00Z').toISOString(),
    escalated: true,
  },
];

export const setMockIssues = (newIssues: Issue[]) => {
  mockIssues = newIssues;
};

// Function to update mock users (e.g., for contractor management)
export const setMockUsers = (newUsers: User[]) => {
    mockUsers = newUsers;
};

// Function to add a user
export const addMockUser = (newUser: User) => {
    mockUsers.push(newUser);
};
